- name: Deploy to EC2
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      cd ~/debtreliefindia/debt_relief_india_ec2
      git fetch --all
      git reset --hard origin/main
      npm install --production
      pm2 stop myapp || true
      pm2 start src/server.js --name "myapp"
